#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil author:nil num:nil creator:nil timestamp:nil toc:nil html-style:nil

#+TITLE: ESafety2
#+AUTHOR: Paul Dougall

#+BEGIN_HTML
  <div class="github-fork-ribbon-wrapper left">
    <div class="github-fork-ribbon">
      <a href="https://github.com/MarcScott/7-CS-ESafety">Fork me on GitHub</a>
    </div>
  </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week1</a></li>
      <li><a href="2_Lesson.html">Week2</a></li>
      <li><a href="3_Lesson.html">Week3</a></li>
      <li><a href="assessment.html">Assessment</a></li>
    </ul>
  </div>
#+END_HTML
* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Social Engineering
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
- Social engineering is the art of manipulating people so that you tell them your personal information.
- Criminals are usually trying to fool you into giving them your passwords, bank information, or access your computer to secretly install malicious software which gives them access to your passwords, bank information and control over your computer.
- Criminals use social engineering tactics because it is usually easier to exploit your natural inclination to trust than it is to discover ways to hack your software.  
- For example, it is much easier to fool someone into giving you their password than it is for you to try hacking their password (unless the password is really weak).
** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:
*Answer the following questions in a text editor such as Word:*
- How good is your current password? Firstly, is it in the most common passwords [[http://www.telegraph.co.uk/technology/2016/01/26/most-common-passwords-revealed---and-theyre-ridiculously-easy-to/][here]]?
- Secondly, test the strength of your password by using the online password [[https://howsecureismypassword.net][checker.]]
- Write down how long it would take to break. 
- Now we are going to try to improve that by reading the above article and watching the video below:
#+BEGIN_HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/t8SQo3R7qeU" frameborder="0" allowfullscreen></iframe>
#+END_HTML 
- What does the article/ video/online checker suggest we do to make our passwords stronger? 
- What in the future are we going to replace passwords with?
- What five tips would you give to someone to making a new secure password? Write them down!
** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:
- In your document say how you have improved your password security i.e how long did it take to break at the start and now with your new password. 
** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:
- We have improved our password, at this point feel free to change your network password, now  we need to protect it from us!
- Look for examples of people being tricked. This article is a good [[http://www.darkreading.com/the-7-best-social-engineering-attacks-ever/d/d-id/1319411][starting]] point.
- The video on this [[http://www.phonearena.com/news/Watch-as-people-are-tricked-into-giving-up-their-passwords_id64905][page]] is good too!
- Think of tips to help us not being deceived into giving out of details.
** Badge It - Silver
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:
- You should already have answered the above questions in full sentences which shows your strength of password at the start of the lesson and then new stronger version. 
- You should have written a 'top 5 tips' on choosing a password.
- Finally from reading the two articles, including the video, write a sentence or two on how to avoid being tricked.
* Malware and Security
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
- Malware is any type of software that is designed to do harm to your computer.
- These might be viruses, adware, spyware, trojan horses, ransomware, scareware or worms.
- Viruses are programs that embed themselves in some other software (including the operating system) on the target system without the user's consent and when that is run causes the virus to spread.    
- Adware is a software that downloads or displays unwanted ads when a user is online, collects marketing data and other information without the user's knowledge or redirects search requests to certain advertising websites. 
- Spyware is a program that  do not spread like viruses; instead they are installed by exploiting security holes. They can also be hidden and packaged together with installed software.
- Trojans are any malicious computer programs which misrepresents itself to appear useful, routine, or interesting in order to persuade a victim to install it. 
- Worms are stand-alone malware programs that actively transmit themselves over a network to infect other computers.
- Ransomware affects an infected computer in some way, and demands payment to reverse the damage.
#+BEGIN_HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/uJRqZTNMCMo" frameborder="0" allowfullscreen></iframe>
#+END_HTML
** Badge It - Gold
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:
- Adding to your written notes to be uploaded, answer the following questions: 
- How do you remove these malicious software programs?
- Prevention is better than cure - give me five tips for avoiding them.
- Find three antivirus programs. Make sure at least one is free and one is paid for.
- What are the differences? 
- What would you recommend?
- Finally, What’s a firewall?  

* Responsible Internet Use
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
*File sharing*
- There are piracy laws protecting the distribution of films and other media. It is illegal to rip a copyrighted DVD or CD and distribute it online. However, peer-to-peer (P2P) file-sharing networks and hosting websites mean it is easy to share files with anyone in the world.
- At which point does sharing a film with others become piracy?

*Software piracy*
- Software piracy is any attempt to break the licence terms of a piece of software. This includes downloading and using a program without paying for it, as well as buying, selling or giving away illegitimate copies of a game or any other piece of software. It could mean extracting code from a program, or modifying it without permission in order to do something that the developers did not wish you to do.
- When you buy software, music or films legally, copyright law forbids you from:
  - giving a copy to a friend
  - making a copy and then selling it
  - using the software on a network (unless the licence allows it, eg it is a business licence)
  - renting the software without the permission of the copyright holder
  - The practice of copying software is a serious problem in some countries. Copying music, films and software illegally means that there is less money available to pay the writers, developers and artists.
  - Some people argue that the incentive to produce new songs, films, television shows and games disappears as a result of piracy.

*Privacy*
- What information can we consider to be private and who owns data? For example, photographs that are uploaded to social networks often legally become the property of the website.
- At what stage can private information like this be used and for what purposes?

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

http://www.bbc.co.uk/bitesize/quiz/q81836819

** Badge It - Platinum
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:
- You have been tasked with coming up with advice for Year 7s. Make a fun document, poster or presentation, that could be given to students to inform them of how to be reponsible online.
